### ISSUE TITLE
rbpnet train command fails: ValueError: No validation loss ('val_loss') found in logs.

### ISSUE THREAD

**Issue by augustboyle** [mhorlacher/rbpnet#2]
I'm not sure I'm running the commands appropriately. I created different BED files for training and validation, made corresponding yml files for each bed file with the same transcriptome-wide bigwigs, and ran rbpnet tfrecord on each yml.

Then I run rbpnet train with the validation tfrecord and the training tfrecord
`rbpnet train --validation-data RPB.val.tfrecord -c configs/model.config.no-penalty.gin -d RBP.train.dataspec.yml -o RBP.h5 RBP.train.tfrecord`

It starts epoch 1 but then throws the following error:
> ValueError: No validation loss ('val_loss') found in logs.
>   In call to configurable 'train' (<function train at 0x2b1be0b4a040>)

Any suggestions?

**Comment by mhorlacher** [comment]
Hi,

I could not reproduce your error. I've created a `develop` branch and added some test data. Could you do the following and let me know whether the error persists? 

1. Activate your rbpnet conda environment
2. Clone `develop` branch: `git clone -b develop https://github.com/mhorlacher/rbpnet.git`
3. Change into repo and install `cd rbpnet; pip install .`
4. Change into example directory and run training: `cd examples; rbpnet train --validation-data data/PTBP1_HepG2.data.tfrecord -c config.gin -d data/PTBP1_HepG2.dataspec.yml -o out/ data/PTBP1_HepG2.data.tfrecord`


Thanks!

**Comment by augustboyle** [comment]
Hi thanks for your help. The example ran, and I was able to do all the modeling I needed! 

I have a question though. You used the same tfrecord for training and validation input: is the validation data meant to be a subset of the training set? I'm still not sure I totally understand how to use those commands.

**Comment by mhorlacher** [comment]
Hi @augustboyle - This was just for debugging purposes. In practice the training and validation sets should not intersect, otherwise one overestimates the model's performance and the model will likely overfit. I'll update the README in the next days and add a more verbose description of the command line arguments, please let me know if you encounter any other issues.
