### ISSUE TITLE
Is the pre-trained model in the article available?

### ISSUE THREAD

**Issue by treblegaia** [mhorlacher/rbpnet#5]
hi, I tried to predict a fasta sequence using all models from biolib and got results, but it seems that I cannot obtain these pre-trained models, such as HNRNPK_HepG2.model.h5, for downstream analysis?

**Comment by mhorlacher** [comment]
Hi @treblegaia, the trained models are available on Zenodo at https://zenodo.org/records/10185223

**Comment by treblegaia** [comment]
Thank you for your quick response and the helpful information!
